In [1]:
import numpy as np

# Task 1: Create a 2D NumPy array of shape (5, 5) filled with random integers between 1 and 100
array = np.random.randint(1, 101, size=(5, 5))
print("Original Array:\n", array)

# Task 2: Extract and print the middle element of the array
middle_element = array[2, 2]
print("\nMiddle Element:", middle_element)

# Task 3: Calculate and print the mean of each row of the array
row_means = np.mean(array, axis=1)
print("\nMean of Each Row:", row_means)

# Task 4: Create a new array with elements greater than the overall mean of the array
overall_mean = np.mean(array)
greater_than_mean = array[array > overall_mean]
print("\nElements Greater than the Overall Mean:", greater_than_mean)

# Task 5: Function to return spiral order of a NumPy matrix
def numpy_spiral_order(matrix):
    result = []
    while matrix.size:
        result.extend(matrix[0])  # Add the first row
        matrix = np.delete(matrix, 0, axis=0)  # Remove the first row
        if matrix.size:
            matrix = np.rot90(matrix)  # Rotate the remaining matrix counter-clockwise
    return result

# Get and print the spiral order of the array
spiral_order = numpy_spiral_order(array)
print("\nSpiral Order:", spiral_order)


Original Array:
 [[58 96 20 73 69]
 [12 92 28 52 85]
 [10 81 29 39  1]
 [62 79 62 99 74]
 [78 53 66 85  8]]

Middle Element: 29

Mean of Each Row: [63.2 53.8 32.  75.2 58. ]

Elements Greater than the Overall Mean: [58 96 73 69 92 85 81 62 79 62 99 74 78 66 85]

Spiral Order: [58, 96, 20, 73, 69, 85, 1, 74, 8, 85, 66, 53, 78, 62, 10, 12, 92, 28, 52, 39, 99, 62, 79, 81, 29]
